[package]
name = "niri-eww-workspaces"
version = "0.1.0"
edition = "2024"

[dependencies]
niri-ipc = { git = "https://github.com/YalteR/niri", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
icon = "0.1.2"