decoration {
    shadow {
    color = rgba(BDB79F55)
    color_inactive = rgba(BDB79F11)
    }
}

plugin {
    hyprbars {
        bar_color = rgb(BDB79F)
        col.text = rgb(48463d)

        hyprbars-button = rgb(BDB79F), 30, ◬, hyprctl dispatch killactive
        hyprbars-button = rgb(BDB79F), 30,▽, hyprctl dispatch fullscreen 1        
    }
}