

exec-once=$HERE/scripts/powercheck
exec-once=$SCRIPTS/portal.sh
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=fcitx5 -d

exec=pkill swayidle; swayidle -w timeout 300 '$LOCK' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep '$LOCK'

general {
    layout = scrolling
	no_focus_fallback = true
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 0

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
	accel_profile = flat
	scroll_method = on_button_down
	scroll_factor = 1

	numlock_by_default = true

    touchpad {
        natural_scroll = false
    }
}

cursor {
    no_hardware_cursors = true
}

dwindle {
    pseudotile=$PSEUDOTILE
}

scrolling {
    explicit_column_widths = 0.333333333333, 0.5, 0.66666666666
    wrap_swapcol = false
    wrap_focus = false
}

gestures {
    gesture=$WORKSPACESWIPEFINGERS,horizontal,workspace
}

xwayland {
    force_zero_scaling=$XZEROSCALING
}

misc {
    disable_hyprland_logo=$DISABLEHYPRLOGO
    animate_manual_resizes=$ANIMATEDRESIZE
    animate_mouse_windowdragging=$ANIMATEDDRAG
}
