import shutil
import subprocess
import sys
import tomllib
from pathlib import Path


HOME = Path('/home/arch')
CACHE_ROOT = HOME / '.cache' / 'matugen' / 'templates'
CONFIG_PATH = HOME / '.config' / 'matugen' / 'config.toml'
GTK_THEME_NAME = 'Matugen'
GTK_THEME_ROOT = HOME / '.themes' / GTK_THEME_NAME
GENERATED_MARKER = 'Generated by matugen'
GTK_BASE_THEME = {
    'gtk3': {
        'light': Path('/usr/share/themes/adw-gtk3/gtk-3.0/gtk.css'),
        'dark': Path('/usr/share/themes/adw-gtk3-dark/gtk-3.0/gtk.css'),
    },
    'gtk4': {
        'light': Path('/usr/share/themes/adw-gtk3/gtk-4.0/gtk.css'),
        'dark': Path('/usr/share/themes/adw-gtk3-dark/gtk-4.0/gtk.css'),
        'libadwaita': Path('/usr/share/themes/adw-gtk3/gtk-4.0/libadwaita.css'),
        'libadwaita_tweaks': Path('/usr/share/themes/adw-gtk3/gtk-4.0/libadwaita-tweaks.css'),
    },
}
BUTTON_OVERRIDE_CSS = """

button,
.button,
dialog button,
messagedialog button,
.dialog-action-area button,
.suggested-action,
.destructive-action {
  background-image: none;
  background-color: @accent_bg_color;
  color: @accent_fg_color;
  border-color: @accent_bg_color;
  box-shadow: none;
}

button:hover,
.button:hover,
dialog button:hover,
messagedialog button:hover,
.dialog-action-area button:hover,
.suggested-action:hover,
.destructive-action:hover {
  background-image: none;
  background-color: alpha(@accent_bg_color, 0.9);
  color: @accent_fg_color;
}

button:active,
.button:active,
dialog button:active,
messagedialog button:active,
.dialog-action-area button:active,
.suggested-action:active,
.destructive-action:active {
  background-image: none;
  background-color: alpha(@accent_bg_color, 0.8);
  color: @accent_fg_color;
}
"""


def _log(message: str) -> None:
    print(message, flush=True)


def _has_command(command: str) -> bool:
    return shutil.which(command) is not None


def _get_command_output(*args: str) -> str | None:
    try:
        result = subprocess.run(args, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip()


def _accent_buttons_enabled() -> bool:
    if not CONFIG_PATH.exists():
        return True

    config = tomllib.loads(CONFIG_PATH.read_text(encoding='utf-8'))
    return bool(config.get('gtk', {}).get('accent_buttons', True))


def _is_generated_file(path: Path) -> bool:
    if not path.exists():
        return False

    try:
        content = path.read_text(encoding='utf-8')
    except UnicodeDecodeError:
        return False
    return GENERATED_MARKER in content


def _backup_path(path: Path) -> Path:
    return path.with_name(f'{path.name}.backup')


def _backup_if_needed(path: Path) -> None:
    if not path.exists() or _is_generated_file(path):
        return

    backup = _backup_path(path)
    if backup.exists():
        return

    backup.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, backup)
    _log(f'Backed up {path} -> {backup}')


def _copy_file(source: Path, target: Path) -> None:
    if not source.exists():
        raise SystemExit(f'Missing generated template: {source}')

    _backup_if_needed(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink():
        target.unlink()
    shutil.copy2(source, target)
    _log(f'Copied {source} -> {target}')


def _write_file(target: Path, content: str) -> None:
    _backup_if_needed(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink():
        target.unlink()
    target.write_text(content, encoding='utf-8')
    _log(f'Wrote {target}')


def _append_button_override(target: Path) -> None:
    if not _accent_buttons_enabled():
        return
    target.write_text(target.read_text(encoding='utf-8') + BUTTON_OVERRIDE_CSS, encoding='utf-8')
    _log(f'Updated {target} with accent button override')


def _gtk_override_loader() -> str:
    return f"""/* {GENERATED_MARKER}. Keep local GTK overrides active. */
@import url("matugen-colors.css");
"""


def _gtk_theme_loader(base_theme: Path) -> str:
    return f"""/* {GENERATED_MARKER}. Wrapper theme around adw-gtk3. */
@import url("{base_theme}");
@import url("matugen-colors.css");
"""


def _gtk4_libadwaita_loader() -> str:
    libadwaita = GTK_BASE_THEME['gtk4']['libadwaita']
    libadwaita_tweaks = GTK_BASE_THEME['gtk4']['libadwaita_tweaks']
    return f"""/* {GENERATED_MARKER}. Extend libadwaita with Matugen colors. */
@import url("{libadwaita}");
@import url("{libadwaita_tweaks}");
@import url("matugen-colors.css");
"""


def _gtk_theme_index() -> str:
    return f"""; {GENERATED_MARKER}.
[Desktop Entry]
Type=X-GNOME-Metatheme
Name={GTK_THEME_NAME}
Comment=Generated Matugen GTK theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme={GTK_THEME_NAME}
MetacityTheme=Default
IconTheme=Adwaita
CursorTheme=Adwaita
ButtonLayout=close,minimize,maximize:
"""


def _read_settings_ini(path: Path) -> list[str]:
    if not path.exists():
        return []
    return path.read_text(encoding='utf-8').splitlines()


def _extract_settings(lines: list[str]) -> dict[str, str]:
    settings: dict[str, str] = {}
    in_settings = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('['):
            in_settings = stripped == '[Settings]'
            continue
        if not in_settings or not stripped or stripped.startswith(';') or '=' not in stripped:
            continue
        key, value = stripped.split('=', 1)
        settings[key.strip()] = value.strip()
    return settings


def _looks_dark(theme_name: str | None) -> bool:
    if not theme_name:
        return False
    return 'dark' in theme_name.lower()


def _current_dark_preference(settings_path: Path) -> bool:
    settings = _extract_settings(_read_settings_ini(settings_path))
    theme_name = settings.get('gtk-theme-name')
    if _looks_dark(theme_name):
        return True

    prefer_dark = settings.get('gtk-application-prefer-dark-theme')
    if prefer_dark is not None:
        return prefer_dark.lower() == 'true'

    if _has_command('gsettings'):
        gtk_theme = _get_command_output('gsettings', 'get', 'org.gnome.desktop.interface', 'gtk-theme')
        if gtk_theme:
            gtk_theme = gtk_theme.strip("'")
            if _looks_dark(gtk_theme):
                return True

        color_scheme = _get_command_output('gsettings', 'get', 'org.gnome.desktop.interface', 'color-scheme')
        if color_scheme:
            return color_scheme.strip("'") == 'prefer-dark'

    return False


def _gtk_settings(current: Path) -> str:
    existing_lines = _read_settings_ini(current)
    dark_preference = 'true' if _current_dark_preference(current) else 'false'
    output: list[str] = [f'; {GENERATED_MARKER}. Previous user-managed version is backed up once.']

    if not existing_lines:
        output.extend([
            '[Settings]',
            f'gtk-theme-name = {GTK_THEME_NAME}',
            f'gtk-application-prefer-dark-theme = {dark_preference}',
            '',
        ])
        return '\n'.join(output)

    in_settings = False
    seen_settings_section = False
    replaced_keys: set[str] = set()

    for line in existing_lines:
        stripped = line.strip()
        if stripped.startswith('['):
            if in_settings and 'gtk-theme-name' not in replaced_keys:
                output.append(f'gtk-theme-name = {GTK_THEME_NAME}')
                replaced_keys.add('gtk-theme-name')
            if in_settings and 'gtk-application-prefer-dark-theme' not in replaced_keys:
                output.append(f'gtk-application-prefer-dark-theme = {dark_preference}')
                replaced_keys.add('gtk-application-prefer-dark-theme')

            in_settings = stripped == '[Settings]'
            if in_settings:
                seen_settings_section = True
            output.append(line)
            continue

        if in_settings and '=' in line:
            key, _value = line.split('=', 1)
            normalized_key = key.strip()
            if normalized_key == 'gtk-theme-name':
                output.append(f'{key.split(key.strip())[0]}gtk-theme-name = {GTK_THEME_NAME}')
                replaced_keys.add(normalized_key)
                continue
            if normalized_key == 'gtk-application-prefer-dark-theme':
                output.append(f'{key.split(key.strip())[0]}gtk-application-prefer-dark-theme = {dark_preference}')
                replaced_keys.add(normalized_key)
                continue

        output.append(line)

    if not seen_settings_section:
        output.extend([
            '[Settings]',
            f'gtk-theme-name = {GTK_THEME_NAME}',
            f'gtk-application-prefer-dark-theme = {dark_preference}',
        ])
    elif in_settings:
        if 'gtk-theme-name' not in replaced_keys:
            output.append(f'gtk-theme-name = {GTK_THEME_NAME}')
        if 'gtk-application-prefer-dark-theme' not in replaced_keys:
            output.append(f'gtk-application-prefer-dark-theme = {dark_preference}')

    output.append('')
    return '\n'.join(output)


def _sync_gtk_gsettings(settings_path: Path) -> None:
    if not _has_command('gsettings'):
        _log('Skipping gsettings sync: command not found')
        return

    color_scheme = 'prefer-dark' if _current_dark_preference(settings_path) else 'default'
    for args in (
        ('gsettings', 'set', 'org.gnome.desktop.interface', 'gtk-theme', GTK_THEME_NAME),
        ('gsettings', 'set', 'org.gnome.desktop.interface', 'color-scheme', color_scheme),
    ):
        try:
            subprocess.run(args, check=True, capture_output=True, text=True)
        except (OSError, subprocess.CalledProcessError) as error:
            _log(f"Skipping {' '.join(args[3:4]) or 'gsettings'} update: {error}")


def sync_gtk(gtk_version: str) -> None:
    source_name = f'matugen-colors-{gtk_version}.css'
    target_root = HOME / '.config' / f'{gtk_version.replace("gtk", "gtk-")}.0'
    theme_root = GTK_THEME_ROOT / f'{gtk_version.replace("gtk", "gtk-")}.0'

    if not target_root.exists():
        _log(f'Skipping {gtk_version} sync: target path not found')
        return

    _log(f'Syncing {gtk_version} template')
    _copy_file(CACHE_ROOT / 'gtk' / source_name, target_root / 'matugen-colors.css')
    _append_button_override(target_root / 'matugen-colors.css')
    settings_path = target_root / 'settings.ini'
    for target, content in (
        (target_root / 'gtk.css', _gtk_override_loader()),
        (target_root / 'gtk-dark.css', _gtk_override_loader()),
        (settings_path, _gtk_settings(settings_path)),
    ):
        _write_file(target, content)

    _copy_file(CACHE_ROOT / 'gtk' / source_name, theme_root / 'matugen-colors.css')
    _append_button_override(theme_root / 'matugen-colors.css')
    for target, content in (
        (theme_root / 'gtk.css', _gtk_theme_loader(GTK_BASE_THEME[gtk_version]['light'])),
        (theme_root / 'gtk-dark.css', _gtk_theme_loader(GTK_BASE_THEME[gtk_version]['dark'])),
    ):
        _write_file(target, content)

    if gtk_version == 'gtk4':
        for target, content in (
            (theme_root / 'libadwaita.css', _gtk4_libadwaita_loader()),
            (theme_root / 'libadwaita-dark.css', _gtk4_libadwaita_loader()),
        ):
            _write_file(target, content)

    index_target = GTK_THEME_ROOT / 'index.theme'
    _write_file(index_target, _gtk_theme_index())
    _sync_gtk_gsettings(settings_path)


def main() -> None:
    if len(sys.argv) != 2 or sys.argv[1] not in ('gtk3', 'gtk4'):
        raise SystemExit(f'Usage: {Path(sys.argv[0]).name} <gtk3|gtk4>')
    sync_gtk(sys.argv[1])


if __name__ == '__main__':
    main()
